import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    domains: [
      "winprofx.com",
      "riverfront.vercel.app",
      "www.homesandlandgoa.com",
      "www.svgrepo.com",
      "res.cloudinary.com",
      "upload.wikimedia.org",
      "cdn.freebiesupply.com",
      "www.shoutlo.com",
      "encrypted-tbn0.gstatic.com",
      "companieslogo.com",
      "pngimg.com",
      "static.vecteezy.com",
      "freelogopng.com",
      "brandlogos.net",
      "images.seeklogo.com",
      "www.cablewirefair.com",
      "static.cdnlogo.com",
      "i.pinimg.com",
      "mahakumbhascent.com",
      "brandeps.com",
      "download.logo.wine",
      "www.pngplay.com",
      "play-lh.googleusercontent.com",
      "mir-s3-cdn-cf.behance.net",
      "getvectorlogo.com",
      "dmjj51nse7bpp.cloudfront.net",
      "seeklogo.com",
      "logowik.com",
      "admin.indiantelevision.com",
      "www.unclechipps.com",
      "1000logos.net",
      "www.jnujaipur.ac.in",
      "www.vedicascholars.com",
      "www.gisbindia.com",
      "ciicpl.com",
      "static.aurouniversity.edu.in",
      "www.reviewadda.com",
      "www.iipm.edu",
      "innovation.opju.ac.in",
      "shooliniuniversity.com",
      "logoeps.com",
      "www.freelogovectors.net",
      "static.wikia.nocookie.net",
      "www.opju.ac.in",
      "bottindia.com",
      "www.integratedlognet.com",
      "www.stellarbinge.com",
      "www.khalsapropertydealers.com",
      "media.istockphoto.com",
    ],
  },
};

export default nextConfig;
