// import type { Metadata } from "next";
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="canonical" href="https://www.bigwigmediadigital.com/" />

        <title>
          BigWig Digital | Result-Driven Digital Marketing Agency in India
        </title>
        <meta
          name="description"
          content="BigWig Digital is a full-service digital marketing agency helping businesses grow with expert SEO, social media marketing, Google Ads, and creative campaigns. Drive traffic, leads, and sales with our proven strategies"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
